### PR TITLE
STUD-4049 Containerd - Part Deux

### PR DESCRIPTION
**Pull request by austinarbor-wk**
## Purpose
Required changes to get commands working on Containerd

## Solution
- Use nerdctl to create the initial container, which sets up network
- Use grpc to execute the tasks and wait for completion

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

- Run chains on a CloudRunner

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by ryancurtin-wk — APPROVED** [review]

**Comment by ryancurtin-wk** [comment]
LGTM.  I don't really have any suggestions for the code, but we have tested pretty extensively.  I think it's as ready as it's going to be.  Deploying to Sandbox and letting it sit for awhile will hopefully give us a good dry-run.  Nice job on getting this over the line!

**Comment by austinarbor-wk** [comment]
QA +1

**Comment by austinarbor-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
