### PR TITLE
STUD-4907 GRPC Instrumentation

### PR DESCRIPTION
**Pull request by austinarbor-wk**
## Purpose

Instrument GRPC with NewRelic

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

- [ ] run the following related examples: **(fill in)**
- [ ] Other necessary steps needed to fully exercise the solution should be added here. **(fill in)**

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by alexandrachakeres-wk — APPROVED** [review]
LGTM, just one thing: is https://jira.atl.workiva.net/browse/STUD-4905 the right ticket? Seems unrelated.

**Comment by austinarbor-wk** [comment]
ah...nope...should have been STUD-4907. Nice catch, case of the mondays

**Comment by austinarbor-wk** [comment]
QA +1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
