### PR TITLE
STUD-3906 Internal Network Resolution Support

### PR DESCRIPTION
**Pull request by austinarbor-wk**
# Description
- Adds more dns options to allow for internal dns resolution
- Bumps fsouza/go-dockerclient

# Acceptance Tests
See https://github.com/OneCloudInc/droplet/pull/498

### CODE REVIEW

**Review by nickmascia-wk — APPROVED** [review]

**Comment by alexwang-wk** [comment]
+10

**Review by alexwang-wk — APPROVED** [review]

**Comment by austinarbor-wk** [comment]
QA +1

**Comment by austinarbor-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
